# Complete and build the Vivado project generated by the repository build.tcl.
# Usage: vivado -mode batch -source tools/vivado_build.tcl

set script_dir [file dirname [file normalize [info script]]]
set repo_dir [file dirname $script_dir]
set project_file [file join $repo_dir vivado State-Estimation State-Estimation.xpr]

if {![file exists $project_file]} {
  error "Vivado project not found at $project_file. Run 'vivado -mode batch -source build.tcl' first."
}

open_project $project_file

set expected_part "xck26-sfvc784-2LV-c"
set actual_part [get_property PART [current_project]]
if {$actual_part ne $expected_part} {
  error "Refusing to build unexpected part '$actual_part'; expected '$expected_part'."
}

set bd_files [get_files -quiet */state_est_bd.bd]
if {[llength $bd_files] != 1} {
  error "Expected exactly one state_est_bd.bd, found [llength $bd_files]."
}
set bd_file [lindex $bd_files 0]

open_bd_design $bd_file
# The initial PS-only platform has no PL AXI slaves. Keep its master ports
# disabled until an addressable peripheral is added to the block design.
set ps_cell [get_bd_cells -quiet zynq_ultra_ps_e_0]
if {[llength $ps_cell] != 1} {
  error "Expected exactly one zynq_ultra_ps_e_0 processing-system cell."
}
set_property -dict [list \
  CONFIG.PSU__USE__M_AXI_GP0 {0} \
  CONFIG.PSU__USE__M_AXI_GP1 {0} \
] $ps_cell
validate_bd_design
save_bd_design
generate_target all $bd_file

set wrapper_files [make_wrapper -files $bd_file -top]
if {[llength [get_files -quiet */state_est_bd_wrapper.v]] == 0} {
  # Keep the make_wrapper result as one Tcl argument so paths containing
  # spaces are not split into separate filenames.
  add_files -norecurse $wrapper_files
}

set_property TOP state_est_bd_wrapper [get_filesets sources_1]
update_compile_order -fileset sources_1

set synth_run [get_runs synth_1]
set synth_status [get_property STATUS $synth_run]
set synth_needs_refresh [get_property NEEDS_REFRESH $synth_run]
if {$synth_needs_refresh || ![string match "*Complete*" $synth_status]} {
  reset_run synth_1
} else {
  puts "BUILD:REUSING_SYNTHESIS=$synth_status"
  reset_run impl_1
}
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

set run_status [get_property STATUS [get_runs impl_1]]
if {![string match "*Complete*" $run_status]} {
  error "Implementation did not complete successfully: $run_status"
}

open_run impl_1

set failing_paths [get_timing_paths -quiet -delay_type max -slack_lesser_than 0 -max_paths 1]
if {[llength $failing_paths] > 0} {
  set worst_slack [get_property SLACK [lindex $failing_paths 0]]
  error "Implementation has a failing setup path with slack $worst_slack ns."
}

set report_dir [get_property DIRECTORY [get_runs impl_1]]
report_timing_summary -file [file join $report_dir timing_summary.rpt]
report_drc -file [file join $report_dir drc.rpt]
set fatal_drc_violations {}
foreach violation [get_drc_violations -quiet] {
  set severity [get_property SEVERITY $violation]
  if {$severity eq "Error" || $severity eq "Critical Warning"} {
    lappend fatal_drc_violations $violation
  }
}
if {[llength $fatal_drc_violations] > 0} {
  error "Implementation has [llength $fatal_drc_violations] Error or Critical Warning DRC violations. See [file join $report_dir drc.rpt]."
}

set bit_file [file join [get_property DIRECTORY [get_runs impl_1]] state_est_bd_wrapper.bit]
if {![file exists $bit_file]} {
  error "Implementation completed but bitstream was not found at $bit_file"
}

puts "BUILD:SUCCESS"
puts "BUILD:PART=$actual_part"
puts "BUILD:BITSTREAM=[file normalize $bit_file]"
puts "BUILD:TIMING=PASS"
puts "BUILD:DRC=PASS"
close_project
